// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Budgeter.Domain.EF.Migrations
{
    [DbContext(typeof(BudgeterContext))]
    internal class BudgeterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Budgeter.Domain.ResourceDelta", b =>
            {
                b.Property<long>("Id");

                b.Property<decimal>("Amount");

                b.Property<long>("CategoryId");

                b.Property<string>("Description")
                    .HasMaxLength(1000);

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.ToTable("ResourceDelta");
            });

            modelBuilder.Entity("Budgeter.Domain.ResourceDeltaCategory", b =>
            {
                b.Property<long>("Id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256);

                b.Property<long?>("ParentCategoryId");

                b.HasKey("Id");

                b.HasIndex("ParentCategoryId");

                b.ToTable("ResourceDeltaCategory");
            });

            modelBuilder.Entity("Budgeter.Domain.ResourceDelta", b =>
            {
                b.HasOne("Budgeter.Domain.ResourceDeltaCategory", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Budgeter.Domain.ResourceDeltaCategory", b =>
            {
                b.HasOne("Budgeter.Domain.ResourceDeltaCategory", "ParentCategory")
                    .WithMany()
                    .HasForeignKey("ParentCategoryId")
                    .OnDelete(DeleteBehavior.Restrict);
            });
#pragma warning restore 612, 618
        }
    }
}